apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policy-controller
  namespace: argocd 
spec:
  generators:
    - git:
        repoURL: https://github.com/mk22042022/testprj.git
        revision: HEAD
        files:
          - path: "policy-controller/**.json"
  template:
    metadata:
      annotations:
        platform: '{{.metadata.annotations.platform}}'
        environment: '{{.metadata.annotations.environment}}'
      name: "policy-controller"
    spec:
      project: default
      source:
        repoURL: https://github.com/mk22042022/testprj
        targetRevision: HEAD
        path: policy-controller
        helm:
           ignoreMissingValueFiles: true
           valueFiles:
             {{- if eq .metadata.annotations.platform "g" }}
             - values-g.yaml
             {{- else if eq .metadata.annotations.platform "a" }}
             - values-a.yaml
             {{- end }}
             {{- if and (eq .metadata.annotations.platform "a") (eq .metadata.annotations.environment "t") }}
             - values-u.yaml
             {{- end }}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: cosign-system
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
