{{- if .Values.cosign.enable -}}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    policy.sigstore.dev/include: "true"
    kubernetes.io/metadata.name: default
  name: default
spec:
  finalizers:
  - kubernetes
{{- end }}
{{- if .Values.cip.create -}}
---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: "**"
  - glob: "index.docker.io/alpine**"
  - glob: "index.docker.io/google**"
  authorities:
    - static:
        action: pass
---
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret-common
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  images:
    {{- range $imageName, $image := .Values.images }}
    {{- if ne $imageName "s-e" }}
    - glob: "{{ .Values.environment.imageRegistry }}/{{ $imageName }}**"
    {{- end }}
    {{- end }}
  authorities:
    - key:
        secretRef:
          name: cosignsecret
