apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: "**"
  - glob: "index.docker.io/alpine**"
  - glob: "index.docker.io/google**"
  authorities:
    - static:
        action: pass
