apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: "**"
  - glob: "index.docker.io/alpine**"
  - glob: "index.docker.io/google**"
  authorities:
    - static:
        action: pass
---
apiVersion: v1
kind: Namespace
metadata:
  name: cosign-system
---
apiVersion: v1
kind: Secret
metadata:
  name: cosignsecret
  namespace: cosign-system
type: Opaque
data:
  cosign.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFdFZvZFhYS2FZMThTQTE4bmV6d2tRbVgwY1RmSAo5bDRpUHFvWVpkekhhSWdCaGh4VzBjYTZCYmhPVFBOV2ltK2tGUDB4c3l0S1R5WTRRdlowUE05Qm5nPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
---
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret-common
spec:
  images:
    - glob: "aaa/bbb**"
    {{- range $i, $imagename := .Values.images }}
    - glob: "eee/{{ $i }}**"
    - glob: "{{ print .Values.environment }}/ggg**"
    - glob: "{{ .Values.environment.imageregistry }}/ggg**"
    {{- end }}
  authorities:
    - key:
        secretRef:
          name: cosignsecret
