---
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret
  annotations: 
    argocd.argoproj.io/sync-wave: "-100"
spec:
  images:
    - glob: "cgr.dev/chainguard**"
    - glob: "gcr.io/tekton-releases**"
    - glob: "gcr.io/kaniko-project**"
    - glob: "gcr.io/cloud-sql-connectors**"
    - glob: "docker.io/library**"
    - glob: "index.docker.io/library**"
    - glob: "index.docker.io/alpine**"
    - glob: "index.docker.io/google**"
    - glob: "index.docker.io/redis**"
    - glob: "us-docker.pkg.dev/saca-common/gcr.io/secure-env**"
    - glob: "sacaregistry.azurecr.io/saca-common/az_packer**"
    - glob: "sacaregistry.azurecr.io/saca-common/secure-env**"
  authorities:
    - static:
        action: pass
---
