{{- if .Values.cosign-env-dev -}}
apiVersion: v1
kind: Namespace
metadata:
  name:dev
  labels:
    policy.sigstore.dev/include: "true"
{{- end }}
{{- if .Values.cip.create -}}
---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: "**"
  - glob: "index.docker.io/alpine**"
  - glob: "index.docker.io/google**"
  authorities:
    - static:
        action: pass
---
apiVersion: v1
kind: Namespace
metadata:
  name: cosign-system
---
apiVersion: v1
kind: Secret
metadata:
  name: cosignsecret
  namespace: cosign-system
type: Opaque
data:
  cosign.pub: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUm1KpwIivxVRieSpeYf9s5dZrbyS
    xEzvE6seUbg/QxpolJlSf5kvvHq2vTFZW1JlKA+RYnXKsAumH/Jt2bDZYA==
    -----END PUBLIC KEY-----
---
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret-common
spec:
  images:
    - glob: "aaa/bbb**"
  authorities:
    - key:
        secretRef:
          name: cosignsecret
{{- end }}
