apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cip-key-secret
  annotations: 
    argocd.argoproj.io/sync-wave: "-100"
spec:
  images:
    - glob: "docker.io/library**"
 authorities:
    - static:
        action: pass
---
